tic;
Matrix = csvread('cleveland-train.csv', 1, 0);
Y = Matrix(:, 14);
X = Matrix(:, 1:13);
[w, e_in] = logistic_reg(X, Y, 10000);
train_error = find_test_error( w, X, Y );
mtrx = csvread('cleveland-test.csv', 1, 0);
y = mtrx(:, 14);
x = mtrx(:, 1:13);
test_error = find_test_error( w, x, y );
time = toc;
tic;
Matrix = csvread('cleveland-train.csv', 1, 0);
Y = Matrix(:, 14);
X = Matrix(:, 1:13);
[b, dev] = glmfit(X, Y, 'binomial');
train_error = find_test_error(transpose(b), X, Y);
mtrx = csvread('cleveland-test.csv', 1, 0);
y = mtrx(:, 14);
x = mtrx(:, 1:13);
test_error = find_test_error(transpose(b), x, y);
time = toc;